export const TeamLogos: Record<string, string> = {
    "3": "/NFL_logos/Chicago_Bears_logo.png",
    "16": "/NFL_logos/Minnesota_Vikings_logo.png",
    "2": "/NFL_logos/Buffalo_Bills_logo.png",
    "33": "/NFL_logos/Baltimore_Ravens_logo.png",
    "14": "/NFL_logos/Los_Angeles_Rams_logo.png",
    "34": "/NFL_logos/Houston_Texans_logo.png",
    "9": "/NFL_logos/Green_Bay_Packers_logo.png",
    "8": "/NFL_logos/Detroit_Lions_logo.png",
    "26": "/NFL_logos/Seattle_Seahawks_logo.png",
    "25": "/NFL_logos/San_Francisco_49ers_logo.png",
    "7": "/NFL_logos/Denver_Broncos_logo.png",
    "10": "/NFL_logos/Tennessee_Titans_logo.png",
    "30": "/NFL_logos/Jacksonville_Jaguars_logo.png",
    "29": "/NFL_logos/Carolina_Panthers_logo.png",
    "28": "/NFL_logos/Washington_Commanders_logo.png",
    "19": "/NFL_logos/New_York_Giants_logo.png",
    "20": "/NFL_logos/New_York_Jets_logo.png",
    "23": "/NFL_logos/Pittsburgh_Steelers_logo.png",
    "18": "/NFL_logos/New_Orleans_Saints_logo.png",
    "22": "/NFL_logos/Arizona_Cardinals_logo.png",
    "17": "/NFL_logos/New_England_Patriots_logo.png",
    "13": "/NFL_logos/Las_Vegas_Raiders_logo.png",
    "11": "/NFL_logos/Indianapolis_Colts_logo.png",
    "15": "/NFL_logos/Miami_Dolphins_logo.png",
    "5": "/NFL_logos/Cleveland_Browns_logo.png",
    "4": "/NFL_logos/Cincinnati_Bengals_logo.png",
    "1": "/NFL_logos/Atlanta_Falcons_logo.png",
    "27": "/NFL_logos/Tampa_Bay_Buccaneers_logo.png",
    "24": "/NFL_logos/NFL_Chargers_logo.png",
    "12": "/NFL_logos/Kansas_City_Chiefs_logo.png",
    "21": "/NFL_logos/Philadelphia_Eagles_logo.png",
    "6": "/NFL_logos/Dallas_Cowboys.png",
}



