using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace backend.Models
{
    // TODO: Add our response variables: Total Points, Spread, MoneyLine
    // This is where we need to aggregate all the data for each team
    // Need to look at all the data we have and decide what is necessary and helpful for each model
    public class PredictionData
    {
        public int SeasonYear { get; set; }
        public int WeekNumber { get; set; }
        public bool NuetralSite { get; set; }
        public bool DivisionCompetition { get; set; }
        public bool ConferenceCompetition { get; set; }
        public bool HomeWinner { get; set; }
        public int HomeWins { get; set; }
        public int HomeLosses { get; set; }
        public decimal HomeAveragePointsAgainst { get; set; }
        public decimal HomeAveragePointsFor { get; set; }
        public decimal HomePointDifferential { get; set; }
        public int HomeStreak { get; set; }
        public decimal HomeWinPercent { get; set; }
        public int HomeDivisionWins { get; set; }
        public int HomeDivisionLosses { get; set; }
        public int HomeTeamHomeWins { get; set; }
        public int HomeTeamHomeLosses { get; set; }
        public int HomeTeamAwayWins { get; set; }
        public int HomeTeamAwayLosses { get; set; }
        public int HomeConferenceWins { get; set; }
        public int HomeConferenceLosses { get; set; }
        public int HomeTeamMlWins { get; set; }
        public int HomeTeamMlLosses { get; set; }
        public int HomeTeamSpreadWins { get; set; }
        public int HomeTeamSpreadLosses { get; set; }
        public int HomeInjuryCount { get; set; }
        public bool AwayWinner { get; set; }
        public int AwayWins { get; set; }
        public int AwayLosses { get; set; }
        public decimal AwayAveragePointsAgainst { get; set; }
        public decimal AwayAveragePointsFor { get; set; }
        public decimal AwayPointDifferential { get; set; }
        public int AwayStreak { get; set; }
        public decimal AwayWinPercent { get; set; }
        public int AwayDivisionWins { get; set; }
        public int AwayDivisionLosses { get; set; }
        public int AwayTeamHomeWins { get; set; }
        public int AwayTeamHomeLosses { get; set; }
        public int AwayTeamAwayWins { get; set; }
        public int AwayTeamAwayLosses { get; set; }
        public int AwayConferenceWins { get; set; }
        public int AwayConferenceLosses { get; set; }
        public int AwayTeamMlWins { get; set; }
        public int AwayTeamMlLosses { get; set; }
        public int AwayTeamSpreadWins { get; set; }
        public int AwayTeamSpreadLosses { get; set; }
        public int AwayInjuryCount { get; set; }
        public decimal AveragePredictedTotal { get; set; }
        public decimal AveragePredictedSpread { get; set; }
        public bool MoneyLineWinner { get; set; }
        public bool SpreadWinner { get; set; }
        public decimal PredictedHomeWinPercent { get; set; }
        public decimal PredicitedHomeMatchupQuality { get; set; }
        public decimal PerdictedHomeOpponentStrenth { get; set; }
        public decimal PredictedHomeLossPercent { get; set; }
        public decimal PredictedHomePointDifferential { get; set; }
        public decimal PredictedAwayWinPercent { get; set; }
        public decimal PredicitedAwayMatchupQuality { get; set; }
        public decimal PerdictedAwayOpponentStrenth { get; set; }
        public decimal PredictedAwayLossPercent { get; set; }
        public decimal PredictedAwayPointDifferential { get; set; }
        public decimal HomeQbr { get; set; }
        public decimal HomeCompletionPercent { get; set; }
        public decimal HomeNetPassYardsPerGame { get; set; }
        public decimal HomePassingBigPlays { get; set; }
        public decimal HomeScrimmageYardsPerGame { get; set; }
        public decimal HomeYardsPerPassAttempt { get; set; }
        public decimal HomeRbRating { get; set; }
        public decimal HomeRushYardsPerGame { get; set; }
        public decimal HomeYardsPerRushAttempt { get; set; }
        public decimal HomeRushingTouchdowns { get; set; }
        public decimal HomeWrRating { get; set; }
        public decimal HomeReceivingTouchdowns { get; set; }
        public decimal HomeReceivingYardsPerGame { get; set; }
        public decimal HomeAverageSackYards { get; set; }
        public decimal HomeAverageStuffYards { get; set; }
        public decimal HomeDefensiveTouchdowns { get; set; }
        public decimal HomeSacks { get; set; }
        public decimal HomeYardsAllowed { get; set; }
        public decimal HomeInterceptions { get; set; }
        public decimal HomeExtraPointPercentage { get; set; }
        public decimal HomeFieldGoalPercent { get; set; }
        public decimal HomeFieldGoalsMade { get; set; }
        public decimal HomeTotalKickFields { get; set; }
        public decimal HomeYardsPerKickReturn { get; set; }
        public decimal HomeYardsPerPuntReturn { get; set; }
        public decimal HomeNetAveragePuntYards { get; set; }
        public decimal HomePuntsInsideTwenty { get; set; }
        public decimal HomedefensivePoints { get; set; }
        public decimal HomeFieldGoalPoint { get; set; }
        public decimal HomePassingTouchdowns { get; set; }
        public decimal HomeTotalPoints { get; set; }
        public decimal HomeFirstDownsPerGame { get; set; }
        public decimal HomeFourthDownConvserionPercent { get; set; }
        public decimal HomeRedZoneEfficiencyPercent { get; set; }
        public decimal HomeTurnoverDifferential { get; set; }
        public decimal AwayQbr { get; set; }
        public decimal AwayCompletionPercent { get; set; }
        public decimal AwayNetPassYardsPerGame { get; set; }
        public decimal AwayPassingBigPlays { get; set; }
        public decimal AwayScrimmageYardsPerGame { get; set; }
        public decimal AwayYardsPerPassAttempt { get; set; }
        public decimal AwayRbRating { get; set; }
        public decimal AwayRushYardsPerGame { get; set; }
        public decimal AwayYardsPerRushAttempt { get; set; }
        public decimal AwayRushingTouchdowns { get; set; }
        public decimal AwayWrRating { get; set; }
        public decimal AwayReceivingTouchdowns { get; set; }
        public decimal AwayReceivingYardsPerGame { get; set; }
        public decimal AwayAverageSackYards { get; set; }
        public decimal AwayAverageStuffYards { get; set; }
        public decimal AwayDefensiveTouchdowns { get; set; }
        public decimal AwaySacks { get; set; }
        public decimal AwayYardsAllowed { get; set; }
        public decimal AwayInterceptions { get; set; }
        public decimal AwayExtraPointPercentage { get; set; }
        public decimal AwayFieldGoalPercent { get; set; }
        public decimal AwayFieldGoalsMade { get; set; }
        public decimal AwayTotalKickFields { get; set; }
        public decimal AwayYardsPerKickReturn { get; set; }
        public decimal AwayYardsPerPuntReturn { get; set; }
        public decimal AwayNetAveragePuntYards { get; set; }
        public decimal AwayPuntsInsideTwenty { get; set; }
        public decimal AwaydefensivePoints { get; set; }
        public decimal AwayFieldGoalPoint { get; set; }
        public decimal AwayPassingTouchdowns { get; set; }
        public decimal AwayTotalPoints { get; set; }
        public decimal AwayFirstDownsPerGame { get; set; }
        public decimal AwayFourthDownConvserionPercent { get; set; }
        public decimal AwayRedZoneEfficiencyPercent { get; set; }
        public decimal AwayTurnoverDifferential { get; set; }
    }
}